#!/bin/bash
echo "Start of backup: $(date)" > /home/dani/twitter/last_mirror.log
# Tweets
docker run --rm \
	   -v /home/dani/code/pdata:/mnt \
	   -v /home/dani/twitter:/data dogsheep \
	   twitter-to-sqlite user-timeline \
	   --since \
	   --auth /mnt/auths/twitter_auth.json \
	   /data/twitter.db
echo "$(date) | Tweets updated" >> /home/dani/twitter/last_mirror.log
# Followers
docker run --rm \
	   -v /home/dani/code/pdata:/mnt \
	   -v /home/dani/twitter:/data dogsheep \
	   twitter-to-sqlite followers \
	   --auth /mnt/auths/twitter_auth.json \
	   /data/twitter.db
echo "$(date) | Followers updated" >> /home/dani/twitter/last_mirror.log
# Friends
docker run --rm \
	   -v /home/dani/code/pdata:/mnt \
	   -v /home/dani/twitter:/data dogsheep \
	   twitter-to-sqlite friends \
	   --auth /mnt/auths/twitter_auth.json \
	   /data/twitter.db
echo "$(date) | Friends updated" >> /home/dani/twitter/last_mirror.log
# Favorites
docker run --rm \
	   -v /home/dani/code/pdata:/mnt \
	   -v /home/dani/twitter:/data dogsheep \
	   twitter-to-sqlite favorites \
	   --auth /mnt/auths/twitter_auth.json \
	   /data/twitter.db
echo "$(date) | Favorites updated" >> /home/dani/twitter/last_mirror.log
# Lists
docker run --rm \
	   -v /home/dani/code/pdata:/mnt \
	   -v /home/dani/twitter:/data dogsheep \
	   twitter-to-sqlite lists \
	   --auth /mnt/auths/twitter_auth.json \
	   /data/twitter.db \
	   --members darribas
echo "$(date) | Lists updated" >> /home/dani/twitter/last_mirror.log

echo "Completed: $(date)" >> /home/dani/twitter/last_mirror.log
