#!/bin/bash
docker run --rm -v /home/dani/code/pdata:/mnt -v /home/dani/github:/data dogsheep \
		    python /mnt/gh/mirror.py \
                    --verbose \
                    --log_file /data/last_mirror.log \
                    --log_mode "w" \
                    /data/github.db \
                    /data/ \
                    /mnt/auths/github_auth.json

